#!/usr/bin/env bash
#
# Run all dotfiles installers.

cd "$(dirname $)"

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

if [ ! -d git ] ;
then
  fail "You should be launching script from 'dotfiles' dir with ./script/install"
fi

# find the installers and run them iteratively
find . -name install.sh -exec /bin/sh -c \{\} \;
