#!/usr/bin/env bash
#
# Run all dotfiles installers.

cd "$(dirname $)"

DOTFILES_ROOT="`pwd`"
source "${DOTFILES_ROOT}/script/shared/common.sh"

if [ ! -d git ] ;
then
  fail "You should be launching script from 'dotfiles' dir with ./script/install"
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
